//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDriver_Basics_and_Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDriver_Basics_and_Locators.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elatmanv5.
        /// </summary>
        internal static string Company_ID {
            get {
                return ResourceManager.GetString("Company_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://azure-env035.elateral.com/.
        /// </summary>
        internal static string Env_Url {
            get {
                return ResourceManager.GetString("Env_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraField_{91873EC0-28D2-4135-9001-6B51EADE6B8C}.
        /// </summary>
        internal static string Id_of_Cost_to_Run {
            get {
                return ResourceManager.GetString("Id_of_Cost_to_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mscqa123.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e96dad0b-b6a4-4bb7-8c2d-90032d2a4b67.
        /// </summary>
        internal static string Target_vendor {
            get {
                return ResourceManager.GetString("Target_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://azure-env035.elateral.com/admin/.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alexb.
        /// </summary>
        internal static string User_auth_id {
            get {
                return ResourceManager.GetString("User_auth_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qauser.
        /// </summary>
        internal static string User_ID {
            get {
                return ResourceManager.GetString("User_ID", resourceCulture);
            }
        }
    }
}
